const products = [
    {
        id: 0,
        category: 'animal products',
        subcategory: 'animal products',
        name: 'eggs',
        price: '995.24 CFA',
    },
    {
        id: 1,
        category: 'animal products',
        subcategory: 'animal products',
        name: 'exotic eggs',
        price: '1337.69',
    },
    {
        id: 2,
        category: 'animal products',
        subcategory: 'animal products',
        name: 'local eggs',
        price: '936.39 CFA',
    },
    {
        id: 3,
        category: 'animal products',
        subcategory: 'animal products',
        name: 'milk',
        price: '3745.54 CFA',
    },
    {
        id: 4,
        category: 'animal products',
        subcategory: 'animal products',
        name: 'Nile Perch',
        price: '3600 CFA',
    },
    {
        id: 5,
        category: 'animal products',
        subcategory: 'animal products',
        name: 'Processed Honey',
        price: '4280.62 CFA',
    },
    {
        id: 6,
        category: 'animal products',
        subcategory: 'animal products',
        name: 'Tilapia',
        price: '3210.47 CFA',
    },
    {
        id: 7,
        category: 'animal products',
        subcategory: 'animal products',
        name: 'Unprocessed Honey',
        price: '5350.78 CFA',
    },
    {
        id: 8,
        category: 'animal products',
        subcategory: 'livestock',
        name: 'Beef',
        price: '1872.77 CFA',
    },
    {
        id: 9,
        category: 'animal products',
        subcategory: 'livestock',
        name: 'Goat Meat',
        price: '2033.29 CFA',
    },
    {
        id: 10,
        category: 'animal products',
        subcategory: 'livestock',
        name: 'Pork',
        price: '1739 CFA',
    },
    {
        id: 11,
        category: 'animal products',
        subcategory: 'poultry',
        name: 'Local Chicken',
        price: '1423.31 CFA',
    },
    {
        id: 12,
        category: 'animal products',
        subcategory: 'poultry',
        name: 'Exotic Chicken',
        price: '1605.23 CFA',
    },
    {
        id: 13,
        category: 'animal products',
        subcategory: 'poultry',
        name: 'Turkey',
        price: '1872.77 CFA',
    },
    {
        id: 14,
        category: 'beans',
        subcategory: 'beans',
        name: 'Agwedde Beans',
        price: '535.08 CFA',
    },
    {
        id: 15,
        category: 'beans',
        subcategory: 'beans',
        name: 'Beans',
        price: '401.31 CFA',
    },
    {
        id: 16,
        category: 'beans',
        subcategory: 'beans',
        name: 'Beans (K132)',
        price: '451 CFA',
    },
    {
        id: 17, 
        category: 'beans',
        subcategory: 'beans',
        name: 'Canadian Beans',
        price: '481.57 CFA',
    },
    {
        id: 18,
        category: 'beans',
        subcategory: 'beans',
        name: 'Mwitemania Beans',
        price: '490 CFA',
    },
    {
        id: 19,
        category: 'beans',
        subcategory: 'beans',
        name: 'Rosecoco Beans',
        price: '451 CFA',
    },
    {
        id: 20,
        category: 'beans',
        subcategory: 'beans',
        name: 'Black Beans',
        price: '535.08 CFA',
    },
    {
        id: 21,
        category: 'beans',
        subcategory: 'beans',
        name: 'Dolichos (Njahi)',
        price: '536 CFA',
    },
    {
        id: 22,
        category: 'beans',
        subcategory: 'beans',
        name: 'Green Gram',
        price: '540 CFA',
    },
    {
        id: 23,
        category: 'beans',
        subcategory: 'beans',
        name: 'Kidney Beans',
        price: '540 CFA',
    },
    {
        id: 24,
        category: 'beans',
        subcategory: 'beans',
        name: 'Mixed Beans',
        price: '545 CFA',
    },
    {
        id: 25,
        category: 'beans',
        subcategory: 'beans',
        name: 'Mwezi Moja',
        price: '500 CFA',
    },
    {
        id: 26,
        category: 'beans',
        subcategory: 'beans',
        name: 'Nambale Beans',
        price: '495 CFA',
    },
]